name: PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "Swift Profile Recorder"
      python_lint_check_enabled: false
      docs_check_enabled: false
      format_check_enabled: false

  swift-test:
    name: Run tests
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      enable_linux_static_sdk_build: true
      linux_pre_build_command: "apt-get update && apt-get -yy install libc6-dbg && apt-get -yy install libc6-prof || true"
      linux_exclude_swift_versions: "[{\"swift_version\": \"5.9\"}]]"
      linux_os_versions: "[\"noble\", \"jammy\"]"
      linux_env_vars: |
        why_PROTOBUF_NO_PROTOC=we_do_not_need_protoc_and_macOS_builders_do_not_have_network
        PROTOBUF_NO_PROTOC=true
        DEBIAN_FRONTEND=noninteractive
        why_LD_LIBRARY_PATH=old_Ubuntus_need_this_to_enable_frame_pointers,_all_fine_from_24.04
        LD_LIBRARY_PATH=/lib/libc6-prof/x86_64-linux-gnu:/lib/libc6-prof/aarch64-linux-gnu
      macos_env_vars: |
        why_PROTOBUF_NO_PROTOC=we_do_not_need_protoc_and_macOS_builders_do_not_have_network
        PROTOBUF_NO_PROTOC=true
      enable_macos_checks: true
      windows_swift_versions: "[]"
      enable_windows_checks: false
      enable_windows_docker: false

  cxx-interop:
    name: Cxx interop
    uses: apple/swift-nio/.github/workflows/cxx_interop.yml@main

  static-sdk:
    name: Static SDK
    # Workaround https://github.com/nektos/act/issues/1875
    uses: apple/swift-nio/.github/workflows/static_sdk.yml@main

  macos-tests:
    name: macOS tests
    uses: apple/swift-nio/.github/workflows/macos_tests.yml@main
    with:
      runner_pool: general
      build_scheme: swift-profile-recorder-Package
      env_vars: "{\"PROTOBUF_NO_PROTOC\": \"true\"}"

  release-builds:
    name: Release builds
    uses: apple/swift-nio/.github/workflows/release_builds.yml@main
